---
# handlers file for tomcat_setup
- name: Start the Tomcat Server
  command: nohup ./tomcatup
  args:
    chdir: /usr/local/bin/

- name: Restart Tomcat Server
  command: ./tomcatdown ; nohup ./tomcatup
  args:
    chdir: /usr/local/bin/
