---
- name: Create user using vars
  hosts: all
  become: true
  gather_facts: yes
  vars:
    user_name: jaganath

  tasks:
    - name: Create a user using user_name
      user:
        name: "{{ user_name }}"

    - name: Create a temp directory for new user in /opt directory
      file:
        path: /opt/{{ user_name }}_temp
        state: directory
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        mode: 0755
