---
- name: installing multiple packages using python list
  hosts: all
  become: true
  gather_facts: yes

  tasks:
    - name: Installing multiple packages using python list instead of with_items
      yum:
        name: ['git', 'tree', 'gzip']
        state: installed
