---
- name: Create multiple users using loop 
  hosts: all
  become: true
  gather_facts: yes

  tasks:
    - name: task to create users using loop
      user:
        name: "{{ item }}"
        state: present
      loop:
        - rama
        - krishna
